name: "SpotifyIntegration"
author: "Twasi Team"
version: "1.0"
main: net.twasidependency.socialmedia.spotify.SpotifyDependency
dependency: true
api: |

  type SpotifyIntegration {
    account: SpotifyAccount,
    authenticationUri: String,

  }

  type SpotifyAccount {
    userName: String,
    premium: Boolean
    logout: Boolean
  }
